title: "זה קל!"
description: "הסברים פשוטים וברורים בעברית למונחי טכנולוגיה, מחשבים, תכנות ואנגלית. המדריך המלא למתחילים ומתקדמים כאן ב'זה קל!'"
baseurl: ""
url: "https://ze-kal.top"
language: "he"
logo: "/assets/images/logo.png" # Important for SEO Tag

theme: null

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

navbar:
  - title: "בית"
    url: /
  - title: "כל הנושאים"
    url: /#topics # Consider linking to specific topic pages if available
  - title: "מילים נפוצות"
    url: /#common-words # Consider linking to specific word list pages
  - title: "תכנות ומחשבים"
    url: /#programming-and-computers # Consider linking to specific tech pages
  - title: "ערוץ יוטיוב"
    url: /youtube-channel.html
  - title: "אודות"
    url: /#about # Link to section on home page
  - title: "משוב"
    url: /#feedback # Link to section on home page

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

permalink: /:categories/:title.html

google_fonts:
  - family: "Rubik"
    variants: "300,400,500,700"

# Optional: SEO Tag specific configurations
social:
   name: Ze Kal!
   links:
     - https://github.com/nhlocal/ZeKal
     - https://www.youtube.com/@Ze-Kal