title: "זה קל! | מונחי טכנולוגיה בקלות"
description: "המדריך המקיף והפשוט שלך להבנת מונחי טכנולוגיה, מחשבים ותכנות בעברית. הסברים ברורים לכל רמה."
baseurl: "/ZeKal" # נדרש עבור GitHub Pages
url: "https://nhlocal.github.io" # URL האתר
language: "he"
logo: "/assets/images/logo.png" # (Optional) Add a path to your logo image

# תבנית Jekyll שתשמש (נשתמש בעיצוב מותאם אישית)
theme: null

# תוספים
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# הגדרות ניווט (נשאר דומה, העיצוב ישפיע על המראה)
navbar:
  - title: "בית"
    url: /index.md
  - title: "כל הנושאים"
    url: /index.html#topics
  - title: "מילים נפוצות"
    url: /index.html#common-words
  - title: "תכנות ומחשבים"
    url: /index.html#programming-and-computers
  - title: "ערוץ יוטיוב"
    url: /youtube-channel.html
  - title: "אודות"
    url: /index.html#about
  - title: "משוב"
    url: /index.html#feedback

# הגדרות שפה וכיוון טקסט
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# פלט אתר
permalink: /:categories/:title.html

# Google Fonts (נשאר Rubik, אפשר לגוון אם רוצים)
google_fonts:
  - family: "Rubik"
    variants: "300,400,500,700" # הוספת משקלים נוספים

# הגדרות נוספות (אם נדרש)
# مثلا, הגדרות ברירת מחדל לפוסטים
# defaults:
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"