title: "זה קל!"
description: "קבל את כל המידע על מונחי טכנולוגיה ומחשבים בפשטות ובקלות"
baseurl: "/ZeKal" # נדרש עבור GitHub Pages
url: "https://nhlocal.github.io" # URL האתר
language: "he"

# תבנית Jekyll שתשמש (נשתמש בעיצוב מותאם אישית)
theme: null

# תוספים
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# הגדרות ניווט
navbar:
  - title: "בית"
    url: /index.html
  - title: "כל הנושאים"
    url: /index.html#topics
  - title: "מילים נפוצות"
    url: /index.html#common-words
  - title: "תכנות ומחשבים"
    url: /index.html#programming-and-computers
  - title: "ערוץ יוטיוב"
    url: /youtube-channel.html
  - title: "אודות"
    url: /index.html#about
  - title: "משוב"
    url: /index.html#feedback

# הגדרות שפה וכיוון טקסט
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# פלט אתר
permalink: /:categories/:title.html

# Google Fonts
google_fonts:
  - family: "Rubik"
    variants: "400,500,700"