title: "זה קל!"
description: "קבל את כל המידע על מונחי טכנולוגיה ומחשבים בפשטות ובקלות"
baseurl: "/ZeKal" # נדרש עבור GitHub Pages
url: "https://nhlocal.github.io" # URL האתר
language: "he"

# תבנית Jekyll שתשמש (נשתמש בעיצוב מותאם אישית)
theme: null

# תוספים
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# הגדרות ניווט
navbar:
  - title: "בית"
    url: "/"
  - title: "נושאים"
    url: "#topics"
  - title: "ערוץ יוטיוב"
    url: "/youtube-channel.html"
  - title: "אודות"
    url: "#about"
  - title: "משוב"
    url: "#feedback"

# הגדרות שפה וכיוון טקסט
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# פלט אתר
permalink: /:categories/:title.html

# Google Fonts
google_fonts:
  - family: "Rubik"
    variants: "400,500,700"
