# File: Gemfile
source "https://rubygems.org"

# Specify Jekyll version
gem "jekyll", "~> 4.3.4"

# Jekyll Plugins
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17"
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-sitemap", "~> 1.4"
end

# Windows and JRuby specific gems for timezone data
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# JRuby specific gem version lock
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]